-- Production-safe dry run for the 70-product Biorona catalog.
-- This transaction always rolls back.
begin;

do $validation$
declare
  bad_categories text;
begin
  select string_agg(required_name, ', ' order by required_name)
    into bad_categories
  from unnest(ARRAY['Buket Fresh Flower', 'Buket Artificial', 'Standing Flower', 'Bloom Box', 'Anggrek dalam Vase', 'Custom Arrangement / Vase', 'Bunga Papan / Ucapan', 'Hampers & Gift']::text[]) required_name
  where not exists (
    select 1
    from public.categories c
    where lower(btrim(c.name)) = lower(btrim(required_name))
      and c.is_active = true
  );

  if bad_categories is not null then
    raise exception 'Kategori tidak ditemukan atau tidak aktif: %', bad_categories;
  end if;
end
$validation$;

with candidates (sku, slug, name, category_name, price, original_price, short_description, description, seo_description, colors, occasions, tags, available, preorder, featured, bestseller, is_active, sort_order, lead_time) as (
  values
    ('BFR-001', 'mawar-pagi-bogor', 'Mawar Pagi Bogor', 'Buket Fresh Flower', 185000, NULL, 'Mawar Pagi Bogor, rangkaian value pilihan untuk momen istimewa.', 'Mawar Pagi Bogor dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Mawar Pagi Bogor untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['merah','putih']::text[], ARRAY['ulang-tahun','romantis']::text[], ARRAY['value','mawar']::text[], true, false, false, true, true, 10, 'same day'),
    ('BFR-002', 'peony-blush-bouquet', 'Peony Blush Bouquet', 'Buket Fresh Flower', 475000, 525000, 'Peony Blush Bouquet, rangkaian signature pilihan untuk momen istimewa.', 'Peony Blush Bouquet dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Peony Blush Bouquet untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['blush','pink']::text[], ARRAY['romantis','anniversary']::text[], ARRAY['signature','peony']::text[], true, false, true, false, true, 11, 'H-1'),
    ('BFR-003', 'serenade-putih', 'Serenade Putih', 'Buket Fresh Flower', 225000, NULL, 'Serenade Putih, rangkaian value pilihan untuk momen istimewa.', 'Serenade Putih dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Serenade Putih untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['putih','hijau']::text[], ARRAY['simpati','kelulusan']::text[], ARRAY['value','mawar']::text[], true, false, false, false, true, 12, 'same day'),
    ('BFR-004', 'biorona-roses-noir', 'Biorona Roses Noir', 'Buket Fresh Flower', 650000, 725000, 'Biorona Roses Noir, rangkaian premium pilihan untuk momen istimewa.', 'Biorona Roses Noir dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Biorona Roses Noir untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['merah','hitam']::text[], ARRAY['romantis','anniversary']::text[], ARRAY['premium','roses']::text[], true, false, true, true, true, 13, 'H-1'),
    ('BFR-005', 'sunshine-gerbera', 'Sunshine Gerbera', 'Buket Fresh Flower', 165000, NULL, 'Sunshine Gerbera, rangkaian value pilihan untuk momen istimewa.', 'Sunshine Gerbera dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Sunshine Gerbera untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['kuning','putih']::text[], ARRAY['ulang-tahun','semangat']::text[], ARRAY['value','gerbera']::text[], true, false, false, false, true, 14, 'same day'),
    ('BFR-006', 'lavender-field-bouquet', 'Lavender Field Bouquet', 'Buket Fresh Flower', 365000, NULL, 'Lavender Field Bouquet, rangkaian signature pilihan untuk momen istimewa.', 'Lavender Field Bouquet dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Lavender Field Bouquet untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['ungu','putih']::text[], ARRAY['ulang-tahun','terima-kasih']::text[], ARRAY['signature','lilac']::text[], true, false, false, false, true, 15, 'H-1'),
    ('BFR-007', 'tulip-kiss', 'Tulip Kiss', 'Buket Fresh Flower', 575000, 625000, 'Tulip Kiss, rangkaian premium pilihan untuk momen istimewa.', 'Tulip Kiss dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Tulip Kiss untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['pink','hijau']::text[], ARRAY['romantis','anniversary']::text[], ARRAY['premium','tulip']::text[], true, false, true, false, true, 16, 'H-2'),
    ('BFR-008', 'senja-cibinong', 'Senja Cibinong', 'Buket Fresh Flower', 325000, NULL, 'Senja Cibinong, rangkaian signature pilihan untuk momen istimewa.', 'Senja Cibinong dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Senja Cibinong untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['peach','oranye']::text[], ARRAY['terima-kasih','ulang-tahun']::text[], ARRAY['signature','peach']::text[], true, false, false, true, true, 17, 'same day'),
    ('BFR-009', 'white-lily-grace', 'White Lily Grace', 'Buket Fresh Flower', 420000, NULL, 'White Lily Grace, rangkaian signature pilihan untuk momen istimewa.', 'White Lily Grace dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan White Lily Grace untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['putih','hijau']::text[], ARRAY['simpati','grand-opening']::text[], ARRAY['signature','lily']::text[], true, false, false, false, true, 18, 'H-1'),
    ('BFR-010', 'coral-charm', 'Coral Charm', 'Buket Fresh Flower', 245000, NULL, 'Coral Charm, rangkaian value pilihan untuk momen istimewa.', 'Coral Charm dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Coral Charm untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['coral','putih']::text[], ARRAY['ulang-tahun','kelulusan']::text[], ARRAY['value','coral']::text[], true, false, false, false, true, 19, 'same day'),
    ('BFR-011', 'gardenia-romance', 'Gardenia Romance', 'Buket Fresh Flower', 725000, 800000, 'Gardenia Romance, rangkaian premium pilihan untuk momen istimewa.', 'Gardenia Romance dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Gardenia Romance untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['pink','putih','hijau']::text[], ARRAY['anniversary','lamaran']::text[], ARRAY['premium','garden-style']::text[], true, false, true, false, true, 20, 'H-2'),
    ('BFR-012', 'daisy-daylight', 'Daisy Daylight', 'Buket Fresh Flower', 175000, NULL, 'Daisy Daylight, rangkaian value pilihan untuk momen istimewa.', 'Daisy Daylight dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Daisy Daylight untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['putih','kuning']::text[], ARRAY['semangat','terima-kasih']::text[], ARRAY['value','daisy']::text[], true, false, false, false, true, 21, 'same day'),
    ('BFR-013', 'ruby-anniversary', 'Ruby Anniversary', 'Buket Fresh Flower', 395000, 450000, 'Ruby Anniversary, rangkaian signature pilihan untuk momen istimewa.', 'Ruby Anniversary dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Ruby Anniversary untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['merah','putih']::text[], ARRAY['anniversary','romantis']::text[], ARRAY['signature','anniversary']::text[], true, false, false, true, true, 22, 'H-1'),
    ('BFR-014', 'meadow-of-hope', 'Meadow of Hope', 'Buket Fresh Flower', 585000, NULL, 'Meadow of Hope, rangkaian premium pilihan untuk momen istimewa.', 'Meadow of Hope dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Meadow of Hope untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['pink','ungu','hijau']::text[], ARRAY['kelulusan','terima-kasih']::text[], ARRAY['premium','meadow']::text[], true, false, false, false, true, 23, 'H-2'),
    ('BAR-001', 'everlasting-rose-mini', 'Everlasting Rose Mini', 'Buket Artificial', 145000, NULL, 'Everlasting Rose Mini, rangkaian value pilihan untuk momen istimewa.', 'Everlasting Rose Mini dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Everlasting Rose Mini untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['merah','putih']::text[], ARRAY['ulang-tahun','terima-kasih']::text[], ARRAY['value','artificial']::text[], true, false, false, true, true, 30, 'same day'),
    ('BAR-002', 'dusty-pink-keepsake', 'Dusty Pink Keepsake', 'Buket Artificial', 275000, NULL, 'Dusty Pink Keepsake, rangkaian signature pilihan untuk momen istimewa.', 'Dusty Pink Keepsake dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Dusty Pink Keepsake untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['dusty-pink','putih']::text[], ARRAY['romantis','anniversary']::text[], ARRAY['signature','artificial']::text[], true, false, false, false, true, 31, 'same day'),
    ('BAR-003', 'forever-sunflower', 'Forever Sunflower', 'Buket Artificial', 165000, NULL, 'Forever Sunflower, rangkaian value pilihan untuk momen istimewa.', 'Forever Sunflower dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Forever Sunflower untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['kuning','hijau']::text[], ARRAY['semangat','kelulusan']::text[], ARRAY['value','sunflower']::text[], true, false, false, false, true, 32, 'same day'),
    ('BAR-004', 'biorona-eternal-luxe', 'Biorona Eternal Luxe', 'Buket Artificial', 475000, 525000, 'Biorona Eternal Luxe, rangkaian premium pilihan untuk momen istimewa.', 'Biorona Eternal Luxe dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Biorona Eternal Luxe untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['pink','cream']::text[], ARRAY['anniversary','romantis']::text[], ARRAY['premium','artificial']::text[], true, false, true, false, true, 33, 'H-1'),
    ('BAR-005', 'lilac-memory', 'Lilac Memory', 'Buket Artificial', 295000, NULL, 'Lilac Memory, rangkaian signature pilihan untuk momen istimewa.', 'Lilac Memory dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Lilac Memory untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['ungu','putih']::text[], ARRAY['terima-kasih','ulang-tahun']::text[], ARRAY['signature','lilac']::text[], true, false, false, false, true, 34, 'same day'),
    ('BAR-006', 'pastel-cloud', 'Pastel Cloud', 'Buket Artificial', 195000, NULL, 'Pastel Cloud, rangkaian value pilihan untuk momen istimewa.', 'Pastel Cloud dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Pastel Cloud untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['pink','biru','putih']::text[], ARRAY['kelulusan','ulang-tahun']::text[], ARRAY['value','pastel']::text[], true, false, false, false, true, 35, 'same day'),
    ('BAR-007', 'noir-rose-keepsake', 'Noir Rose Keepsake', 'Buket Artificial', 325000, NULL, 'Noir Rose Keepsake, rangkaian signature pilihan untuk momen istimewa.', 'Noir Rose Keepsake dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Noir Rose Keepsake untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['hitam','merah']::text[], ARRAY['romantis','anniversary']::text[], ARRAY['signature','noir']::text[], true, false, false, true, true, 36, 'H-1'),
    ('BAR-008', 'champagne-peony', 'Champagne Peony', 'Buket Artificial', 425000, NULL, 'Champagne Peony, rangkaian premium pilihan untuk momen istimewa.', 'Champagne Peony dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Champagne Peony untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['champagne','cream']::text[], ARRAY['anniversary','terima-kasih']::text[], ARRAY['premium','peony']::text[], true, false, true, false, true, 37, 'H-1'),
    ('BAR-009', 'blue-hydrangea-note', 'Blue Hydrangea Note', 'Buket Artificial', 210000, NULL, 'Blue Hydrangea Note, rangkaian value pilihan untuk momen istimewa.', 'Blue Hydrangea Note dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Blue Hydrangea Note untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['biru','hijau']::text[], ARRAY['kelulusan','semangat']::text[], ARRAY['value','hydrangea']::text[], true, false, false, false, true, 38, 'same day'),
    ('BAR-010', 'ivory-love-story', 'Ivory Love Story', 'Buket Artificial', 310000, NULL, 'Ivory Love Story, rangkaian signature pilihan untuk momen istimewa.', 'Ivory Love Story dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Ivory Love Story untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['ivory','putih']::text[], ARRAY['lamaran','anniversary']::text[], ARRAY['signature','ivory']::text[], true, false, false, false, true, 39, 'H-1'),
    ('BAR-011', 'terracotta-bloom', 'Terracotta Bloom', 'Buket Artificial', 340000, 375000, 'Terracotta Bloom, rangkaian signature pilihan untuk momen istimewa.', 'Terracotta Bloom dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Terracotta Bloom untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['terracotta','cream']::text[], ARRAY['housewarming','terima-kasih']::text[], ARRAY['signature','boho']::text[], true, false, false, false, true, 40, 'H-1'),
    ('BAR-012', 'rose-gold-forever', 'Rose Gold Forever', 'Buket Artificial', 455000, NULL, 'Rose Gold Forever, rangkaian premium pilihan untuk momen istimewa.', 'Rose Gold Forever dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Rose Gold Forever untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['rose-gold','pink']::text[], ARRAY['anniversary','ulang-tahun']::text[], ARRAY['premium','rose-gold']::text[], true, false, false, true, true, 41, 'H-1'),
    ('STF-001', 'sympathy-white-stand', 'Sympathy White Stand', 'Standing Flower', 750000, NULL, 'Sympathy White Stand, rangkaian value pilihan untuk momen istimewa.', 'Sympathy White Stand dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Sympathy White Stand untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['putih','hijau']::text[], ARRAY['duka-cita','simpati']::text[], ARRAY['value','sympathy']::text[], true, false, false, true, true, 50, 'H-1'),
    ('STF-002', 'grand-opening-gold', 'Grand Opening Gold', 'Standing Flower', 1250000, NULL, 'Grand Opening Gold, rangkaian signature pilihan untuk momen istimewa.', 'Grand Opening Gold dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Grand Opening Gold untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['kuning','oranye','hijau']::text[], ARRAY['grand-opening','bisnis']::text[], ARRAY['signature','opening']::text[], true, false, true, false, true, 51, 'H-1'),
    ('STF-003', 'tribute-in-lilac', 'Tribute in Lilac', 'Standing Flower', 1100000, NULL, 'Tribute in Lilac, rangkaian signature pilihan untuk momen istimewa.', 'Tribute in Lilac dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Tribute in Lilac untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['ungu','putih']::text[], ARRAY['duka-cita','simpati']::text[], ARRAY['signature','tribute']::text[], true, false, false, false, true, 52, 'H-1'),
    ('STF-004', 'celebration-cascade', 'Celebration Cascade', 'Standing Flower', 1850000, 2050000, 'Celebration Cascade, rangkaian premium pilihan untuk momen istimewa.', 'Celebration Cascade dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Celebration Cascade untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['pink','putih','hijau']::text[], ARRAY['grand-opening','peresmian']::text[], ARRAY['premium','celebration']::text[], true, false, true, false, true, 53, 'H-2'),
    ('STF-005', 'condolence-serenity', 'Condolence Serenity', 'Standing Flower', 825000, NULL, 'Condolence Serenity, rangkaian value pilihan untuk momen istimewa.', 'Condolence Serenity dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Condolence Serenity untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['putih','cream']::text[], ARRAY['duka-cita','simpati']::text[], ARRAY['value','condolence']::text[], true, false, false, false, true, 54, 'H-1'),
    ('STF-006', 'royal-red-welcome', 'Royal Red Welcome', 'Standing Flower', 1650000, NULL, 'Royal Red Welcome, rangkaian premium pilihan untuk momen istimewa.', 'Royal Red Welcome dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Royal Red Welcome untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['merah','hijau']::text[], ARRAY['grand-opening','bisnis']::text[], ARRAY['premium','red']::text[], true, false, false, true, true, 55, 'H-2'),
    ('STF-007', 'pastel-congratulations', 'Pastel Congratulations', 'Standing Flower', 1150000, NULL, 'Pastel Congratulations, rangkaian signature pilihan untuk momen istimewa.', 'Pastel Congratulations dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Pastel Congratulations untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['pink','peach','putih']::text[], ARRAY['kelulusan','peresmian']::text[], ARRAY['signature','pastel']::text[], true, false, false, false, true, 56, 'H-1'),
    ('STF-008', 'sunrise-business-bloom', 'Sunrise Business Bloom', 'Standing Flower', 900000, NULL, 'Sunrise Business Bloom, rangkaian value pilihan untuk momen istimewa.', 'Sunrise Business Bloom dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Sunrise Business Bloom untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['kuning','oranye']::text[], ARRAY['grand-opening','bisnis']::text[], ARRAY['value','business']::text[], true, false, false, false, true, 57, 'H-1'),
    ('STF-009', 'orchid-ceremony-stand', 'Orchid Ceremony Stand', 'Standing Flower', 1950000, NULL, 'Orchid Ceremony Stand, rangkaian premium pilihan untuk momen istimewa.', 'Orchid Ceremony Stand dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Orchid Ceremony Stand untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['putih','ungu','hijau']::text[], ARRAY['peresmian','corporate']::text[], ARRAY['premium','orchid']::text[], true, false, true, false, true, 58, 'H-2'),
    ('STF-010', 'peaceful-farewell', 'Peaceful Farewell', 'Standing Flower', 1350000, NULL, 'Peaceful Farewell, rangkaian signature pilihan untuk momen istimewa.', 'Peaceful Farewell dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Peaceful Farewell untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['putih','hijau']::text[], ARRAY['duka-cita','simpati']::text[], ARRAY['signature','farewell']::text[], true, false, false, false, true, 59, 'H-1'),
    ('STF-011', 'biorona-victory-stand', 'Biorona Victory Stand', 'Standing Flower', 1750000, 1900000, 'Biorona Victory Stand, rangkaian premium pilihan untuk momen istimewa.', 'Biorona Victory Stand dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Biorona Victory Stand untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['merah','emas','hijau']::text[], ARRAY['corporate','grand-opening']::text[], ARRAY['premium','victory']::text[], true, false, true, false, true, 60, 'H-2'),
    ('STF-012', 'joyful-milestone', 'Joyful Milestone', 'Standing Flower', 1200000, NULL, 'Joyful Milestone, rangkaian signature pilihan untuk momen istimewa.', 'Joyful Milestone dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Joyful Milestone untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['pink','kuning','putih']::text[], ARRAY['kelulusan','peresmian']::text[], ARRAY['signature','milestone']::text[], true, false, false, true, true, 61, 'H-1'),
    ('BLB-001', 'petit-rose-box', 'Petit Rose Box', 'Bloom Box', 210000, NULL, 'Petit Rose Box, rangkaian value pilihan untuk momen istimewa.', 'Petit Rose Box dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Petit Rose Box untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['merah','putih']::text[], ARRAY['romantis','ulang-tahun']::text[], ARRAY['value','rose-box']::text[], true, false, false, true, true, 70, 'same day'),
    ('BLB-002', 'blush-bloom-box', 'Blush Bloom Box', 'Bloom Box', 385000, NULL, 'Blush Bloom Box, rangkaian signature pilihan untuk momen istimewa.', 'Blush Bloom Box dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Blush Bloom Box untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['blush','pink']::text[], ARRAY['anniversary','romantis']::text[], ARRAY['signature','blush']::text[], true, false, true, false, true, 71, 'H-1'),
    ('BLB-003', 'midnight-roses-box', 'Midnight Roses Box', 'Bloom Box', 625000, 690000, 'Midnight Roses Box, rangkaian premium pilihan untuk momen istimewa.', 'Midnight Roses Box dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Midnight Roses Box untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['merah','hitam']::text[], ARRAY['romantis','anniversary']::text[], ARRAY['premium','roses']::text[], true, false, true, true, true, 72, 'H-1'),
    ('BLB-004', 'sunny-note-box', 'Sunny Note Box', 'Bloom Box', 235000, NULL, 'Sunny Note Box, rangkaian value pilihan untuk momen istimewa.', 'Sunny Note Box dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Sunny Note Box untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['kuning','putih']::text[], ARRAY['terima-kasih','semangat']::text[], ARRAY['value','sunny']::text[], true, false, false, false, true, 73, 'same day'),
    ('BLB-005', 'ivory-lullaby', 'Ivory Lullaby', 'Bloom Box', 360000, NULL, 'Ivory Lullaby, rangkaian signature pilihan untuk momen istimewa.', 'Ivory Lullaby dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Ivory Lullaby untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['ivory','putih']::text[], ARRAY['simpati','terima-kasih']::text[], ARRAY['signature','ivory']::text[], true, false, false, false, true, 74, 'H-1'),
    ('BLB-006', 'violet-kiss-box', 'Violet Kiss Box', 'Bloom Box', 410000, NULL, 'Violet Kiss Box, rangkaian signature pilihan untuk momen istimewa.', 'Violet Kiss Box dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Violet Kiss Box untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['ungu','pink']::text[], ARRAY['ulang-tahun','romantis']::text[], ARRAY['signature','violet']::text[], true, false, false, false, true, 75, 'H-1'),
    ('BLB-007', 'sweet-peach-garden', 'Sweet Peach Garden', 'Bloom Box', 275000, NULL, 'Sweet Peach Garden, rangkaian value pilihan untuk momen istimewa.', 'Sweet Peach Garden dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Sweet Peach Garden untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['peach','cream']::text[], ARRAY['ulang-tahun','terima-kasih']::text[], ARRAY['value','peach']::text[], true, false, false, false, true, 76, 'same day'),
    ('BLB-008', 'biorona-signature-box', 'Biorona Signature Box', 'Bloom Box', 750000, 825000, 'Biorona Signature Box, rangkaian premium pilihan untuk momen istimewa.', 'Biorona Signature Box dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Biorona Signature Box untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['pink','cream','hijau']::text[], ARRAY['anniversary','lamaran']::text[], ARRAY['premium','signature']::text[], true, false, true, false, true, 77, 'H-2'),
    ('BLB-009', 'daisy-cheer-box', 'Daisy Cheer Box', 'Bloom Box', 225000, NULL, 'Daisy Cheer Box, rangkaian value pilihan untuk momen istimewa.', 'Daisy Cheer Box dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Daisy Cheer Box untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['putih','kuning']::text[], ARRAY['kelulusan','semangat']::text[], ARRAY['value','daisy']::text[], true, false, false, false, true, 78, 'same day'),
    ('BLB-010', 'red-velvet-bloom', 'Red Velvet Bloom', 'Bloom Box', 445000, 495000, 'Red Velvet Bloom, rangkaian signature pilihan untuk momen istimewa.', 'Red Velvet Bloom dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Red Velvet Bloom untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['merah','hitam']::text[], ARRAY['anniversary','romantis']::text[], ARRAY['signature','red-velvet']::text[], true, false, false, true, true, 79, 'H-1'),
    ('BLB-011', 'blue-moon-bloom-box', 'Blue Moon Bloom Box', 'Bloom Box', 575000, NULL, 'Blue Moon Bloom Box, rangkaian premium pilihan untuk momen istimewa.', 'Blue Moon Bloom Box dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Blue Moon Bloom Box untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['biru','putih']::text[], ARRAY['ulang-tahun','kelulusan']::text[], ARRAY['premium','blue']::text[], true, false, false, false, true, 80, 'H-2'),
    ('BLB-012', 'caramel-garden-box', 'Caramel Garden Box', 'Bloom Box', 395000, NULL, 'Caramel Garden Box, rangkaian signature pilihan untuk momen istimewa.', 'Caramel Garden Box dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Caramel Garden Box untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['caramel','cream','hijau']::text[], ARRAY['terima-kasih','housewarming']::text[], ARRAY['signature','earthy']::text[], true, false, false, false, true, 81, 'H-1'),
    ('ANG-001', 'phalaenopsis-putih-classic', 'Phalaenopsis Putih Classic', 'Anggrek dalam Vase', 325000, NULL, 'Phalaenopsis Putih Classic, rangkaian value pilihan untuk momen istimewa.', 'Phalaenopsis Putih Classic dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Phalaenopsis Putih Classic untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['putih','hijau']::text[], ARRAY['housewarming','terima-kasih']::text[], ARRAY['value','orchid']::text[], true, false, false, true, true, 90, 'same day'),
    ('ANG-002', 'orchid-lilac-serene', 'Orchid Lilac Serene', 'Anggrek dalam Vase', 475000, NULL, 'Orchid Lilac Serene, rangkaian signature pilihan untuk momen istimewa.', 'Orchid Lilac Serene dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Orchid Lilac Serene untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['ungu','putih']::text[], ARRAY['ulang-tahun','terima-kasih']::text[], ARRAY['signature','orchid']::text[], true, false, false, false, true, 91, 'H-1'),
    ('ANG-003', 'golden-orchid-vase', 'Golden Orchid Vase', 'Anggrek dalam Vase', 850000, 925000, 'Golden Orchid Vase, rangkaian premium pilihan untuk momen istimewa.', 'Golden Orchid Vase dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Golden Orchid Vase untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['kuning','hijau']::text[], ARRAY['corporate','grand-opening']::text[], ARRAY['premium','orchid']::text[], true, false, true, false, true, 92, 'H-2'),
    ('ANG-004', 'orchid-blush-duo', 'Orchid Blush Duo', 'Anggrek dalam Vase', 625000, NULL, 'Orchid Blush Duo, rangkaian signature pilihan untuk momen istimewa.', 'Orchid Blush Duo dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Orchid Blush Duo untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['blush','pink']::text[], ARRAY['anniversary','romantis']::text[], ARRAY['signature','orchid']::text[], true, false, false, true, true, 93, 'H-1'),
    ('ANG-005', 'emerald-orchid-table', 'Emerald Orchid Table', 'Anggrek dalam Vase', 395000, NULL, 'Emerald Orchid Table, rangkaian value pilihan untuk momen istimewa.', 'Emerald Orchid Table dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Emerald Orchid Table untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['putih','hijau']::text[], ARRAY['housewarming','terima-kasih']::text[], ARRAY['value','orchid']::text[], true, false, false, false, true, 94, 'H-1'),
    ('ANG-006', 'royal-purple-orchid', 'Royal Purple Orchid', 'Anggrek dalam Vase', 975000, NULL, 'Royal Purple Orchid, rangkaian premium pilihan untuk momen istimewa.', 'Royal Purple Orchid dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Royal Purple Orchid untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['ungu','hijau']::text[], ARRAY['corporate','anniversary']::text[], ARRAY['premium','orchid']::text[], true, false, true, false, true, 95, 'H-2'),
    ('CAV-001', 'bogor-garden-vase', 'Bogor Garden Vase', 'Custom Arrangement / Vase', 425000, NULL, 'Bogor Garden Vase, rangkaian value pilihan untuk momen istimewa.', 'Bogor Garden Vase dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Bogor Garden Vase untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['pink','putih','hijau']::text[], ARRAY['terima-kasih','housewarming']::text[], ARRAY['value','vase']::text[], true, false, false, false, true, 100, 'H-1'),
    ('CAV-002', 'custom-pastel-harmony', 'Custom Pastel Harmony', 'Custom Arrangement / Vase', 675000, NULL, 'Custom Pastel Harmony, rangkaian signature pilihan untuk momen istimewa.', 'Custom Pastel Harmony dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Custom Pastel Harmony untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['pink','peach','putih']::text[], ARRAY['ulang-tahun','anniversary']::text[], ARRAY['signature','custom']::text[], true, false, true, false, true, 101, 'H-2'),
    ('CAV-003', 'tropical-anthurium-vase', 'Tropical Anthurium Vase', 'Custom Arrangement / Vase', 925000, NULL, 'Tropical Anthurium Vase, rangkaian premium pilihan untuk momen istimewa.', 'Tropical Anthurium Vase dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Tropical Anthurium Vase untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['merah','hijau']::text[], ARRAY['corporate','grand-opening']::text[], ARRAY['premium','tropical']::text[], true, false, false, false, true, 102, 'H-2'),
    ('CAV-004', 'white-ceremony-arrangement', 'White Ceremony Arrangement', 'Custom Arrangement / Vase', 745000, NULL, 'White Ceremony Arrangement, rangkaian signature pilihan untuk momen istimewa.', 'White Ceremony Arrangement dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan White Ceremony Arrangement untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['putih','hijau']::text[], ARRAY['simpati','peresmian']::text[], ARRAY['signature','ceremony']::text[], true, false, false, false, true, 103, 'H-2'),
    ('CAV-005', 'biorona-tableau-luxe', 'Biorona Tableau Luxe', 'Custom Arrangement / Vase', 1250000, 1400000, 'Biorona Tableau Luxe, rangkaian premium pilihan untuk momen istimewa.', 'Biorona Tableau Luxe dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Biorona Tableau Luxe untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['pink','ungu','cream']::text[], ARRAY['anniversary','corporate']::text[], ARRAY['premium','luxe']::text[], true, false, true, true, true, 104, 'H-2'),
    ('CAV-006', 'wildflower-weekend-vase', 'Wildflower Weekend Vase', 'Custom Arrangement / Vase', 485000, NULL, 'Wildflower Weekend Vase, rangkaian value pilihan untuk momen istimewa.', 'Wildflower Weekend Vase dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Wildflower Weekend Vase untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['kuning','ungu','hijau']::text[], ARRAY['housewarming','terima-kasih']::text[], ARRAY['value','wildflower']::text[], true, false, false, false, true, 105, 'H-1'),
    ('BPN-001', 'papan-ucapan-selamat-klasik', 'Papan Ucapan Selamat Klasik', 'Bunga Papan / Ucapan', 650000, NULL, 'Papan Ucapan Selamat Klasik, rangkaian value pilihan untuk momen istimewa.', 'Papan Ucapan Selamat Klasik dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Papan Ucapan Selamat Klasik untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['merah','kuning']::text[], ARRAY['grand-opening','peresmian']::text[], ARRAY['value','bunga-papan']::text[], true, false, false, true, true, 110, 'H-1'),
    ('BPN-002', 'papan-grand-opening-premium', 'Papan Grand Opening Premium', 'Bunga Papan / Ucapan', 1250000, 1400000, 'Papan Grand Opening Premium, rangkaian premium pilihan untuk momen istimewa.', 'Papan Grand Opening Premium dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Papan Grand Opening Premium untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['merah','emas','hijau']::text[], ARRAY['grand-opening','corporate']::text[], ARRAY['premium','bunga-papan']::text[], true, false, true, false, true, 111, 'H-2'),
    ('BPN-003', 'papan-duka-cita-putih', 'Papan Duka Cita Putih', 'Bunga Papan / Ucapan', 850000, NULL, 'Papan Duka Cita Putih, rangkaian signature pilihan untuk momen istimewa.', 'Papan Duka Cita Putih dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Papan Duka Cita Putih untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['putih','hijau']::text[], ARRAY['duka-cita','simpati']::text[], ARRAY['signature','bunga-papan']::text[], true, false, false, false, true, 112, 'H-1'),
    ('BPN-004', 'papan-sukses-cibinong', 'Papan Sukses Cibinong', 'Bunga Papan / Ucapan', 925000, NULL, 'Papan Sukses Cibinong, rangkaian signature pilihan untuk momen istimewa.', 'Papan Sukses Cibinong dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Papan Sukses Cibinong untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['biru','kuning','putih']::text[], ARRAY['peresmian','kelulusan']::text[], ARRAY['signature','bunga-papan']::text[], true, false, false, false, true, 113, 'H-1'),
    ('HMP-001', 'sweet-bloom-hamper', 'Sweet Bloom Hamper', 'Hampers & Gift', 275000, NULL, 'Sweet Bloom Hamper, rangkaian value pilihan untuk momen istimewa.', 'Sweet Bloom Hamper dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Sweet Bloom Hamper untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['pink','cream']::text[], ARRAY['ulang-tahun','terima-kasih']::text[], ARRAY['value','hamper']::text[], true, false, false, true, true, 120, 'H-1'),
    ('HMP-002', 'tea-and-roses-gift', 'Tea and Roses Gift', 'Hampers & Gift', 465000, NULL, 'Tea and Roses Gift, rangkaian signature pilihan untuk momen istimewa.', 'Tea and Roses Gift dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Tea and Roses Gift untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['merah','cream']::text[], ARRAY['terima-kasih','anniversary']::text[], ARRAY['signature','tea-gift']::text[], true, false, false, false, true, 121, 'H-1'),
    ('HMP-003', 'biorona-celebration-hamper', 'Biorona Celebration Hamper', 'Hampers & Gift', 875000, 950000, 'Biorona Celebration Hamper, rangkaian premium pilihan untuk momen istimewa.', 'Biorona Celebration Hamper dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Biorona Celebration Hamper untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['pink','emas','cream']::text[], ARRAY['anniversary','corporate']::text[], ARRAY['premium','celebration']::text[], true, false, true, false, true, 122, 'H-2'),
    ('HMP-004', 'graduation-cheer-gift', 'Graduation Cheer Gift', 'Hampers & Gift', 525000, NULL, 'Graduation Cheer Gift, rangkaian signature pilihan untuk momen istimewa.', 'Graduation Cheer Gift dirancang florist Biorona dengan komposisi warna yang seimbang untuk pengiriman area Bogor dan Cibinong.', 'Pesan Graduation Cheer Gift untuk hadiah dan ucapan berkesan dengan layanan florist Biorona.', ARRAY['biru','kuning']::text[], ARRAY['kelulusan','semangat']::text[], ARRAY['signature','graduation']::text[], true, false, false, true, true, 123, 'H-1')
),
dataset_check as (
  select
    case when count(*) = 70
      and count(distinct sku) = 70
      and count(distinct slug) = 70
      and bool_and(price > 0)
      and bool_and(cardinality(colors) > 0)
      and bool_and(cardinality(occasions) > 0)
      and bool_and(length(btrim(short_description)) > 0)
      and bool_and(length(btrim(description)) > 0)
      and bool_and(length(btrim(seo_description)) > 0)
    then 1 else 0 end as valid
  from candidates
),
resolved as (
  select c.*, cat.id as category_id
  from candidates c
  join public.categories cat
    on lower(btrim(cat.name)) = lower(btrim(c.category_name))
   and cat.is_active = true
  cross join dataset_check d
  where 1 / d.valid = 1
),
classified as (
  select r.*,
    exists (select 1 from public.products p where p.sku = r.sku) as sku_exists,
    exists (select 1 from public.products p where p.slug = r.slug) as slug_exists
  from resolved r
)
select
  (select count(*) from candidates) as candidate_count,
  count(*) filter (where not sku_exists and not slug_exists) as will_insert_count,
  count(*) filter (where sku_exists) as skipped_sku_existing_count,
  count(*) filter (where slug_exists) as skipped_slug_existing_count,
  (select sum(price) from candidates) as candidate_total_price,
  jsonb_object_agg(category_name, category_count order by category_name) as candidate_count_by_category,
  array_agg(sku order by sku) filter (where not sku_exists and not slug_exists) as skus_to_insert
from classified
join (
  select category_name, count(*) as category_count
  from candidates
  group by category_name
) category_totals using (category_name);

rollback;
